### ISSUE TITLE
Confirmation when running M-x ert

### ISSUE THREAD

**Issue by hajovonta** [emacsfodder/etd#2]
There is a confirmation when invoking M-x ert, to run the tests. Is it necessary? I think when M-x ert is invoked explicitly, the user's intention is already clear.

**Comment by jasonm23** [comment]
Note this package is etd, not ert.

**Comment by hajovonta** [comment]
Ah, I see, sorry. Wrong package. :)

**Comment by jasonm23** [comment]
Check out [ert-runner](https://github.com/rejeep/ert-runner.el)
