### ISSUE TITLE
rounding of floating-point numbers

### ISSUE THREAD

**Issue by hajovonta** [emacsfodder/etd#3]
Is there a way to specify a rounding for floating point numbers? It is a bit inconvenient to specify all the numbers, i.e. 4243.827160493827 as result, when 4243.82 would suffice.

**Comment by jasonm23** [comment]
This would be the job of an expectation library, which is not in the initial scope of `etd`.

The current expectation libraries [`ert-expectations`](https://www.emacswiki.org/emacs/ert-expectations.el) and the expect macro in [`buttercup`](https://github.com/jorgenschaefer/emacs-buttercup/) don't handle this, as far as I know.

When an approximate float is acceptable, we can use a function like this...

```emacs-lisp
(defvar precision-factor 1.0e-3)
(defun approx-equal (x y)
  (or (= x y)
      (< (/ (abs (- x y))
            (max (abs x) (abs y)))
         precision-factor)))

(approx-equal 1.2321 1.2322) => t
```

**Comment by jasonm23** [comment]
Because `defexamples` only match on  `=>` which is effectively `equal` it's designed for 1:1 examples.

However, if I add a `~>` matcher meaning, _output is approximately the right side_ that would be ok.

What do you think?  

There would need to be an approximation var, like `precision-factor` in the code above.

**Comment by hajovonta** [comment]
That would be cool! I like the ~> idea.
It would be even better if the precision factor could be a parameter to this matcher somehow, but it's also fine if we would set it in some variable beforehand.

**Comment by jasonm23** [comment]
TBH I don't want to dirty the example syntax very much.  A few symbolic matchers is ok, but I'll start insisting on APL symbols ... (joking? possibly)

**Comment by jasonm23** [comment]
A let which encloses a group of tests should work for (working name) `etd-float-approximation`

I need to test it of course.

(better names are welcome!)

**Comment by jasonm23** [comment]
```
(let ((operator "~>"))
 (pcase operator
   ("~>" (message "that's approximately what I thought"))
   ("=>" (message "that's what I thought"))))
```

`pcase` does it better than `cond`

**Comment by jasonm23** [comment]
Single scalar float approximate comparison is working.

- [ ] Add support for flat lists.
- [ ] Add support for nested lists.

**Comment by jasonm23** [comment]
Oh wait, no it's not...

**Comment by jasonm23** [comment]
I don't know why, `pcase` cases get nil'ed, `cond` may be bulky, but it works.

**Comment by jasonm23** [comment]
Ok, looking good on https://github.com/emacsfodder/kurecolor/runs/8267010300?check_suite_focus=true

Approximation expects correct rounding, not simple truncation.

**Comment by jasonm23** [comment]
https://github.com/emacsfodder/kurecolor/actions/runs/3023245026

2 lists of floats can be approximately equal. (For now they can only be flat lists, not trees.)

I'll merge these changes into etd tomorrow.

**Comment by jasonm23** [comment]
(already merged the changes.
