### ISSUE TITLE
Error matcher?

### ISSUE THREAD

**Issue by jasonm23** [emacsfodder/etd#4]
@hajovonta it occurs to me an error matcher should be available.

- [x] appearance? `=x` | `-!` | `!!` etc. needs to be decided.
- [x] the error called should be the right hand side.
- [ ] a let block will need to be generated for the example in quesiton. It will stub the error function, and collect a call count. 

I think that's all.

**Comment by jasonm23** [comment]
For example...

```lisp
(defexamples my-test-subject
  (my-test-subject 5) !! 'user-error)
```

**Comment by jasonm23** [comment]
I like the first one, iirc it's not used elsewhere in Lisp, but I could be wrong, tough to google for punctuation.

**Comment by hajovonta** [comment]
I'd favor more expressive matcher names, but I'm totally fine with anything that works.
(I know => is common in other languages, but still feels a bit weird to type :)

**Comment by jasonm23** [comment]
Ultimately the emphasis is on the readability side.

The `=>` is used in Emacs docs as is `≣` (for strict equivalence) which may be nicer in the docs output, but entering it is a whole thing with `C-x 8 RET stric...` not fun.

**Comment by jasonm23** [comment]
Eval'd output is always prefixed with `=>` too. (Why it got used in the first place by @magnars (I'd guess))

**Comment by magnars** [comment]
For the historically inclined, my use of `=>` was due to me using the [Midje](https://github.com/marick/Midje) testing library at the time. :)

**Comment by jasonm23** [comment]
That's interesting, they're probably inheriting it from the classic lisp REPL

**Comment by jasonm23** [comment]
Ok so `!!` should be the operator for errors.

My attempt to code this failed. Calling time, for today.

**Comment by jasonm23** [comment]
@hajovonta - closing this one as out of scope.

TBH I think it's best to fall back to ert + ert-expectations + in particular [el-mock](https://github.com/rejeep/el-mock.el)

Potentially I could integrate el-mock into error tests with `!!` at a later date.
